# Schema for the theme setting configuration file of the THEMETITLE theme.
# Change "THEMENAME" to your theme machine name and "THEMETITLE" to your theme human-readable name.

THEMENAME.settings:
  type: theme_settings
  label: 'THEMETITLE settings'
